/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedOrgsNewRouteImport } from './routes/_authenticated/orgs.new'
import { Route as AuthenticatedOrgsOrgIdRouteImport } from './routes/_authenticated/orgs.$orgId'
import { Route as AuthenticatedOrgsOrgIdIndexRouteImport } from './routes/_authenticated/orgs.$orgId.index'
import { Route as ApiPublicV1InvoicesRouteImport } from './routes/api/public/v1/invoices'
import { Route as ApiPublicV1EntriesRouteImport } from './routes/api/public/v1/entries'
import { Route as ApiPublicV1CompanySearchRouteImport } from './routes/api/public/v1/company-search'
import { Route as ApiPublicV1AttachmentsRouteImport } from './routes/api/public/v1/attachments'
import { Route as AuthenticatedOrgsOrgIdSettingsRouteImport } from './routes/_authenticated/orgs.$orgId.settings'
import { Route as AuthenticatedOrgsOrgIdScanRouteImport } from './routes/_authenticated/orgs.$orgId.scan'
import { Route as AuthenticatedOrgsOrgIdReportsRouteImport } from './routes/_authenticated/orgs.$orgId.reports'
import { Route as AuthenticatedOrgsOrgIdMembersRouteImport } from './routes/_authenticated/orgs.$orgId.members'
import { Route as AuthenticatedOrgsOrgIdEntriesRouteImport } from './routes/_authenticated/orgs.$orgId.entries'
import { Route as AuthenticatedOrgsOrgIdBankRouteImport } from './routes/_authenticated/orgs.$orgId.bank'
import { Route as AuthenticatedOrgsOrgIdAttachmentsRouteImport } from './routes/_authenticated/orgs.$orgId.attachments'
import { Route as AuthenticatedOrgsOrgIdApiKeysRouteImport } from './routes/_authenticated/orgs.$orgId.api-keys'
import { Route as AuthenticatedOrgsOrgIdInvoicesIndexRouteImport } from './routes/_authenticated/orgs.$orgId.invoices.index'
import { Route as ApiPublicV1ReportsSummaryRouteImport } from './routes/api/public/v1/reports.summary'
import { Route as ApiPublicV1InvoicesInvoiceIdRouteImport } from './routes/api/public/v1/invoices.$invoiceId'
import { Route as ApiPublicV1EntriesEntryIdRouteImport } from './routes/api/public/v1/entries.$entryId'
import { Route as ApiPublicV1AttachmentsAttachmentIdRouteImport } from './routes/api/public/v1/attachments.$attachmentId'
import { Route as ApiPublicV1AiScanReceiptRouteImport } from './routes/api/public/v1/ai.scan-receipt'
import { Route as AuthenticatedOrgsOrgIdInvoicesInvoiceIdRouteImport } from './routes/_authenticated/orgs.$orgId.invoices.$invoiceId'
import { Route as AuthenticatedOrgsOrgIdBankDiagnosticsRouteImport } from './routes/_authenticated/orgs.$orgId.bank_.diagnostics'
import { Route as AuthenticatedOrgsOrgIdBankCallbackRouteImport } from './routes/_authenticated/orgs.$orgId.bank_.callback'
import { Route as ApiPublicV1InvoicesInvoiceIdSendRouteImport } from './routes/api/public/v1/invoices.$invoiceId.send'
import { Route as ApiPublicV1InvoicesInvoiceIdPdfRouteImport } from './routes/api/public/v1/invoices.$invoiceId.pdf'
import { Route as ApiPublicV1EntriesEntryIdAttachmentsRouteImport } from './routes/api/public/v1/entries.$entryId.attachments'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOrgsNewRoute = AuthenticatedOrgsNewRouteImport.update({
  id: '/orgs/new',
  path: '/orgs/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOrgsOrgIdRoute = AuthenticatedOrgsOrgIdRouteImport.update({
  id: '/orgs/$orgId',
  path: '/orgs/$orgId',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOrgsOrgIdIndexRoute =
  AuthenticatedOrgsOrgIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOrgsOrgIdRoute,
  } as any)
const ApiPublicV1InvoicesRoute = ApiPublicV1InvoicesRouteImport.update({
  id: '/api/public/v1/invoices',
  path: '/api/public/v1/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1EntriesRoute = ApiPublicV1EntriesRouteImport.update({
  id: '/api/public/v1/entries',
  path: '/api/public/v1/entries',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1CompanySearchRoute =
  ApiPublicV1CompanySearchRouteImport.update({
    id: '/api/public/v1/company-search',
    path: '/api/public/v1/company-search',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1AttachmentsRoute = ApiPublicV1AttachmentsRouteImport.update({
  id: '/api/public/v1/attachments',
  path: '/api/public/v1/attachments',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOrgsOrgIdSettingsRoute =
  AuthenticatedOrgsOrgIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedOrgsOrgIdRoute,
  } as any)
const AuthenticatedOrgsOrgIdScanRoute =
  AuthenticatedOrgsOrgIdScanRouteImport.update({
    id: '/scan',
    path: '/scan',
    getParentRoute: () => AuthenticatedOrgsOrgIdRoute,
  } as any)
const AuthenticatedOrgsOrgIdReportsRoute =
  AuthenticatedOrgsOrgIdReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedOrgsOrgIdRoute,
  } as any)
const AuthenticatedOrgsOrgIdMembersRoute =
  AuthenticatedOrgsOrgIdMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthenticatedOrgsOrgIdRoute,
  } as any)
const AuthenticatedOrgsOrgIdEntriesRoute =
  AuthenticatedOrgsOrgIdEntriesRouteImport.update({
    id: '/entries',
    path: '/entries',
    getParentRoute: () => AuthenticatedOrgsOrgIdRoute,
  } as any)
const AuthenticatedOrgsOrgIdBankRoute =
  AuthenticatedOrgsOrgIdBankRouteImport.update({
    id: '/bank',
    path: '/bank',
    getParentRoute: () => AuthenticatedOrgsOrgIdRoute,
  } as any)
const AuthenticatedOrgsOrgIdAttachmentsRoute =
  AuthenticatedOrgsOrgIdAttachmentsRouteImport.update({
    id: '/attachments',
    path: '/attachments',
    getParentRoute: () => AuthenticatedOrgsOrgIdRoute,
  } as any)
const AuthenticatedOrgsOrgIdApiKeysRoute =
  AuthenticatedOrgsOrgIdApiKeysRouteImport.update({
    id: '/api-keys',
    path: '/api-keys',
    getParentRoute: () => AuthenticatedOrgsOrgIdRoute,
  } as any)
const AuthenticatedOrgsOrgIdInvoicesIndexRoute =
  AuthenticatedOrgsOrgIdInvoicesIndexRouteImport.update({
    id: '/invoices/',
    path: '/invoices/',
    getParentRoute: () => AuthenticatedOrgsOrgIdRoute,
  } as any)
const ApiPublicV1ReportsSummaryRoute =
  ApiPublicV1ReportsSummaryRouteImport.update({
    id: '/api/public/v1/reports/summary',
    path: '/api/public/v1/reports/summary',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1InvoicesInvoiceIdRoute =
  ApiPublicV1InvoicesInvoiceIdRouteImport.update({
    id: '/$invoiceId',
    path: '/$invoiceId',
    getParentRoute: () => ApiPublicV1InvoicesRoute,
  } as any)
const ApiPublicV1EntriesEntryIdRoute =
  ApiPublicV1EntriesEntryIdRouteImport.update({
    id: '/$entryId',
    path: '/$entryId',
    getParentRoute: () => ApiPublicV1EntriesRoute,
  } as any)
const ApiPublicV1AttachmentsAttachmentIdRoute =
  ApiPublicV1AttachmentsAttachmentIdRouteImport.update({
    id: '/$attachmentId',
    path: '/$attachmentId',
    getParentRoute: () => ApiPublicV1AttachmentsRoute,
  } as any)
const ApiPublicV1AiScanReceiptRoute =
  ApiPublicV1AiScanReceiptRouteImport.update({
    id: '/api/public/v1/ai/scan-receipt',
    path: '/api/public/v1/ai/scan-receipt',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedOrgsOrgIdInvoicesInvoiceIdRoute =
  AuthenticatedOrgsOrgIdInvoicesInvoiceIdRouteImport.update({
    id: '/invoices/$invoiceId',
    path: '/invoices/$invoiceId',
    getParentRoute: () => AuthenticatedOrgsOrgIdRoute,
  } as any)
const AuthenticatedOrgsOrgIdBankDiagnosticsRoute =
  AuthenticatedOrgsOrgIdBankDiagnosticsRouteImport.update({
    id: '/bank_/diagnostics',
    path: '/bank/diagnostics',
    getParentRoute: () => AuthenticatedOrgsOrgIdRoute,
  } as any)
const AuthenticatedOrgsOrgIdBankCallbackRoute =
  AuthenticatedOrgsOrgIdBankCallbackRouteImport.update({
    id: '/bank_/callback',
    path: '/bank/callback',
    getParentRoute: () => AuthenticatedOrgsOrgIdRoute,
  } as any)
const ApiPublicV1InvoicesInvoiceIdSendRoute =
  ApiPublicV1InvoicesInvoiceIdSendRouteImport.update({
    id: '/send',
    path: '/send',
    getParentRoute: () => ApiPublicV1InvoicesInvoiceIdRoute,
  } as any)
const ApiPublicV1InvoicesInvoiceIdPdfRoute =
  ApiPublicV1InvoicesInvoiceIdPdfRouteImport.update({
    id: '/pdf',
    path: '/pdf',
    getParentRoute: () => ApiPublicV1InvoicesInvoiceIdRoute,
  } as any)
const ApiPublicV1EntriesEntryIdAttachmentsRoute =
  ApiPublicV1EntriesEntryIdAttachmentsRouteImport.update({
    id: '/attachments',
    path: '/attachments',
    getParentRoute: () => ApiPublicV1EntriesEntryIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AuthenticatedAppRoute
  '/orgs/$orgId': typeof AuthenticatedOrgsOrgIdRouteWithChildren
  '/orgs/new': typeof AuthenticatedOrgsNewRoute
  '/orgs/$orgId/api-keys': typeof AuthenticatedOrgsOrgIdApiKeysRoute
  '/orgs/$orgId/attachments': typeof AuthenticatedOrgsOrgIdAttachmentsRoute
  '/orgs/$orgId/bank': typeof AuthenticatedOrgsOrgIdBankRoute
  '/orgs/$orgId/entries': typeof AuthenticatedOrgsOrgIdEntriesRoute
  '/orgs/$orgId/members': typeof AuthenticatedOrgsOrgIdMembersRoute
  '/orgs/$orgId/reports': typeof AuthenticatedOrgsOrgIdReportsRoute
  '/orgs/$orgId/scan': typeof AuthenticatedOrgsOrgIdScanRoute
  '/orgs/$orgId/settings': typeof AuthenticatedOrgsOrgIdSettingsRoute
  '/api/public/v1/attachments': typeof ApiPublicV1AttachmentsRouteWithChildren
  '/api/public/v1/company-search': typeof ApiPublicV1CompanySearchRoute
  '/api/public/v1/entries': typeof ApiPublicV1EntriesRouteWithChildren
  '/api/public/v1/invoices': typeof ApiPublicV1InvoicesRouteWithChildren
  '/orgs/$orgId/': typeof AuthenticatedOrgsOrgIdIndexRoute
  '/orgs/$orgId/bank/callback': typeof AuthenticatedOrgsOrgIdBankCallbackRoute
  '/orgs/$orgId/bank/diagnostics': typeof AuthenticatedOrgsOrgIdBankDiagnosticsRoute
  '/orgs/$orgId/invoices/$invoiceId': typeof AuthenticatedOrgsOrgIdInvoicesInvoiceIdRoute
  '/api/public/v1/ai/scan-receipt': typeof ApiPublicV1AiScanReceiptRoute
  '/api/public/v1/attachments/$attachmentId': typeof ApiPublicV1AttachmentsAttachmentIdRoute
  '/api/public/v1/entries/$entryId': typeof ApiPublicV1EntriesEntryIdRouteWithChildren
  '/api/public/v1/invoices/$invoiceId': typeof ApiPublicV1InvoicesInvoiceIdRouteWithChildren
  '/api/public/v1/reports/summary': typeof ApiPublicV1ReportsSummaryRoute
  '/orgs/$orgId/invoices/': typeof AuthenticatedOrgsOrgIdInvoicesIndexRoute
  '/api/public/v1/entries/$entryId/attachments': typeof ApiPublicV1EntriesEntryIdAttachmentsRoute
  '/api/public/v1/invoices/$invoiceId/pdf': typeof ApiPublicV1InvoicesInvoiceIdPdfRoute
  '/api/public/v1/invoices/$invoiceId/send': typeof ApiPublicV1InvoicesInvoiceIdSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AuthenticatedAppRoute
  '/orgs/new': typeof AuthenticatedOrgsNewRoute
  '/orgs/$orgId/api-keys': typeof AuthenticatedOrgsOrgIdApiKeysRoute
  '/orgs/$orgId/attachments': typeof AuthenticatedOrgsOrgIdAttachmentsRoute
  '/orgs/$orgId/bank': typeof AuthenticatedOrgsOrgIdBankRoute
  '/orgs/$orgId/entries': typeof AuthenticatedOrgsOrgIdEntriesRoute
  '/orgs/$orgId/members': typeof AuthenticatedOrgsOrgIdMembersRoute
  '/orgs/$orgId/reports': typeof AuthenticatedOrgsOrgIdReportsRoute
  '/orgs/$orgId/scan': typeof AuthenticatedOrgsOrgIdScanRoute
  '/orgs/$orgId/settings': typeof AuthenticatedOrgsOrgIdSettingsRoute
  '/api/public/v1/attachments': typeof ApiPublicV1AttachmentsRouteWithChildren
  '/api/public/v1/company-search': typeof ApiPublicV1CompanySearchRoute
  '/api/public/v1/entries': typeof ApiPublicV1EntriesRouteWithChildren
  '/api/public/v1/invoices': typeof ApiPublicV1InvoicesRouteWithChildren
  '/orgs/$orgId': typeof AuthenticatedOrgsOrgIdIndexRoute
  '/orgs/$orgId/bank/callback': typeof AuthenticatedOrgsOrgIdBankCallbackRoute
  '/orgs/$orgId/bank/diagnostics': typeof AuthenticatedOrgsOrgIdBankDiagnosticsRoute
  '/orgs/$orgId/invoices/$invoiceId': typeof AuthenticatedOrgsOrgIdInvoicesInvoiceIdRoute
  '/api/public/v1/ai/scan-receipt': typeof ApiPublicV1AiScanReceiptRoute
  '/api/public/v1/attachments/$attachmentId': typeof ApiPublicV1AttachmentsAttachmentIdRoute
  '/api/public/v1/entries/$entryId': typeof ApiPublicV1EntriesEntryIdRouteWithChildren
  '/api/public/v1/invoices/$invoiceId': typeof ApiPublicV1InvoicesInvoiceIdRouteWithChildren
  '/api/public/v1/reports/summary': typeof ApiPublicV1ReportsSummaryRoute
  '/orgs/$orgId/invoices': typeof AuthenticatedOrgsOrgIdInvoicesIndexRoute
  '/api/public/v1/entries/$entryId/attachments': typeof ApiPublicV1EntriesEntryIdAttachmentsRoute
  '/api/public/v1/invoices/$invoiceId/pdf': typeof ApiPublicV1InvoicesInvoiceIdPdfRoute
  '/api/public/v1/invoices/$invoiceId/send': typeof ApiPublicV1InvoicesInvoiceIdSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_authenticated/orgs/$orgId': typeof AuthenticatedOrgsOrgIdRouteWithChildren
  '/_authenticated/orgs/new': typeof AuthenticatedOrgsNewRoute
  '/_authenticated/orgs/$orgId/api-keys': typeof AuthenticatedOrgsOrgIdApiKeysRoute
  '/_authenticated/orgs/$orgId/attachments': typeof AuthenticatedOrgsOrgIdAttachmentsRoute
  '/_authenticated/orgs/$orgId/bank': typeof AuthenticatedOrgsOrgIdBankRoute
  '/_authenticated/orgs/$orgId/entries': typeof AuthenticatedOrgsOrgIdEntriesRoute
  '/_authenticated/orgs/$orgId/members': typeof AuthenticatedOrgsOrgIdMembersRoute
  '/_authenticated/orgs/$orgId/reports': typeof AuthenticatedOrgsOrgIdReportsRoute
  '/_authenticated/orgs/$orgId/scan': typeof AuthenticatedOrgsOrgIdScanRoute
  '/_authenticated/orgs/$orgId/settings': typeof AuthenticatedOrgsOrgIdSettingsRoute
  '/api/public/v1/attachments': typeof ApiPublicV1AttachmentsRouteWithChildren
  '/api/public/v1/company-search': typeof ApiPublicV1CompanySearchRoute
  '/api/public/v1/entries': typeof ApiPublicV1EntriesRouteWithChildren
  '/api/public/v1/invoices': typeof ApiPublicV1InvoicesRouteWithChildren
  '/_authenticated/orgs/$orgId/': typeof AuthenticatedOrgsOrgIdIndexRoute
  '/_authenticated/orgs/$orgId/bank_/callback': typeof AuthenticatedOrgsOrgIdBankCallbackRoute
  '/_authenticated/orgs/$orgId/bank_/diagnostics': typeof AuthenticatedOrgsOrgIdBankDiagnosticsRoute
  '/_authenticated/orgs/$orgId/invoices/$invoiceId': typeof AuthenticatedOrgsOrgIdInvoicesInvoiceIdRoute
  '/api/public/v1/ai/scan-receipt': typeof ApiPublicV1AiScanReceiptRoute
  '/api/public/v1/attachments/$attachmentId': typeof ApiPublicV1AttachmentsAttachmentIdRoute
  '/api/public/v1/entries/$entryId': typeof ApiPublicV1EntriesEntryIdRouteWithChildren
  '/api/public/v1/invoices/$invoiceId': typeof ApiPublicV1InvoicesInvoiceIdRouteWithChildren
  '/api/public/v1/reports/summary': typeof ApiPublicV1ReportsSummaryRoute
  '/_authenticated/orgs/$orgId/invoices/': typeof AuthenticatedOrgsOrgIdInvoicesIndexRoute
  '/api/public/v1/entries/$entryId/attachments': typeof ApiPublicV1EntriesEntryIdAttachmentsRoute
  '/api/public/v1/invoices/$invoiceId/pdf': typeof ApiPublicV1InvoicesInvoiceIdPdfRoute
  '/api/public/v1/invoices/$invoiceId/send': typeof ApiPublicV1InvoicesInvoiceIdSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/app'
    | '/orgs/$orgId'
    | '/orgs/new'
    | '/orgs/$orgId/api-keys'
    | '/orgs/$orgId/attachments'
    | '/orgs/$orgId/bank'
    | '/orgs/$orgId/entries'
    | '/orgs/$orgId/members'
    | '/orgs/$orgId/reports'
    | '/orgs/$orgId/scan'
    | '/orgs/$orgId/settings'
    | '/api/public/v1/attachments'
    | '/api/public/v1/company-search'
    | '/api/public/v1/entries'
    | '/api/public/v1/invoices'
    | '/orgs/$orgId/'
    | '/orgs/$orgId/bank/callback'
    | '/orgs/$orgId/bank/diagnostics'
    | '/orgs/$orgId/invoices/$invoiceId'
    | '/api/public/v1/ai/scan-receipt'
    | '/api/public/v1/attachments/$attachmentId'
    | '/api/public/v1/entries/$entryId'
    | '/api/public/v1/invoices/$invoiceId'
    | '/api/public/v1/reports/summary'
    | '/orgs/$orgId/invoices/'
    | '/api/public/v1/entries/$entryId/attachments'
    | '/api/public/v1/invoices/$invoiceId/pdf'
    | '/api/public/v1/invoices/$invoiceId/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app'
    | '/orgs/new'
    | '/orgs/$orgId/api-keys'
    | '/orgs/$orgId/attachments'
    | '/orgs/$orgId/bank'
    | '/orgs/$orgId/entries'
    | '/orgs/$orgId/members'
    | '/orgs/$orgId/reports'
    | '/orgs/$orgId/scan'
    | '/orgs/$orgId/settings'
    | '/api/public/v1/attachments'
    | '/api/public/v1/company-search'
    | '/api/public/v1/entries'
    | '/api/public/v1/invoices'
    | '/orgs/$orgId'
    | '/orgs/$orgId/bank/callback'
    | '/orgs/$orgId/bank/diagnostics'
    | '/orgs/$orgId/invoices/$invoiceId'
    | '/api/public/v1/ai/scan-receipt'
    | '/api/public/v1/attachments/$attachmentId'
    | '/api/public/v1/entries/$entryId'
    | '/api/public/v1/invoices/$invoiceId'
    | '/api/public/v1/reports/summary'
    | '/orgs/$orgId/invoices'
    | '/api/public/v1/entries/$entryId/attachments'
    | '/api/public/v1/invoices/$invoiceId/pdf'
    | '/api/public/v1/invoices/$invoiceId/send'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/app'
    | '/_authenticated/orgs/$orgId'
    | '/_authenticated/orgs/new'
    | '/_authenticated/orgs/$orgId/api-keys'
    | '/_authenticated/orgs/$orgId/attachments'
    | '/_authenticated/orgs/$orgId/bank'
    | '/_authenticated/orgs/$orgId/entries'
    | '/_authenticated/orgs/$orgId/members'
    | '/_authenticated/orgs/$orgId/reports'
    | '/_authenticated/orgs/$orgId/scan'
    | '/_authenticated/orgs/$orgId/settings'
    | '/api/public/v1/attachments'
    | '/api/public/v1/company-search'
    | '/api/public/v1/entries'
    | '/api/public/v1/invoices'
    | '/_authenticated/orgs/$orgId/'
    | '/_authenticated/orgs/$orgId/bank_/callback'
    | '/_authenticated/orgs/$orgId/bank_/diagnostics'
    | '/_authenticated/orgs/$orgId/invoices/$invoiceId'
    | '/api/public/v1/ai/scan-receipt'
    | '/api/public/v1/attachments/$attachmentId'
    | '/api/public/v1/entries/$entryId'
    | '/api/public/v1/invoices/$invoiceId'
    | '/api/public/v1/reports/summary'
    | '/_authenticated/orgs/$orgId/invoices/'
    | '/api/public/v1/entries/$entryId/attachments'
    | '/api/public/v1/invoices/$invoiceId/pdf'
    | '/api/public/v1/invoices/$invoiceId/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicV1AttachmentsRoute: typeof ApiPublicV1AttachmentsRouteWithChildren
  ApiPublicV1CompanySearchRoute: typeof ApiPublicV1CompanySearchRoute
  ApiPublicV1EntriesRoute: typeof ApiPublicV1EntriesRouteWithChildren
  ApiPublicV1InvoicesRoute: typeof ApiPublicV1InvoicesRouteWithChildren
  ApiPublicV1AiScanReceiptRoute: typeof ApiPublicV1AiScanReceiptRoute
  ApiPublicV1ReportsSummaryRoute: typeof ApiPublicV1ReportsSummaryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orgs/new': {
      id: '/_authenticated/orgs/new'
      path: '/orgs/new'
      fullPath: '/orgs/new'
      preLoaderRoute: typeof AuthenticatedOrgsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orgs/$orgId': {
      id: '/_authenticated/orgs/$orgId'
      path: '/orgs/$orgId'
      fullPath: '/orgs/$orgId'
      preLoaderRoute: typeof AuthenticatedOrgsOrgIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orgs/$orgId/': {
      id: '/_authenticated/orgs/$orgId/'
      path: '/'
      fullPath: '/orgs/$orgId/'
      preLoaderRoute: typeof AuthenticatedOrgsOrgIdIndexRouteImport
      parentRoute: typeof AuthenticatedOrgsOrgIdRoute
    }
    '/api/public/v1/invoices': {
      id: '/api/public/v1/invoices'
      path: '/api/public/v1/invoices'
      fullPath: '/api/public/v1/invoices'
      preLoaderRoute: typeof ApiPublicV1InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/entries': {
      id: '/api/public/v1/entries'
      path: '/api/public/v1/entries'
      fullPath: '/api/public/v1/entries'
      preLoaderRoute: typeof ApiPublicV1EntriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/company-search': {
      id: '/api/public/v1/company-search'
      path: '/api/public/v1/company-search'
      fullPath: '/api/public/v1/company-search'
      preLoaderRoute: typeof ApiPublicV1CompanySearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/attachments': {
      id: '/api/public/v1/attachments'
      path: '/api/public/v1/attachments'
      fullPath: '/api/public/v1/attachments'
      preLoaderRoute: typeof ApiPublicV1AttachmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/orgs/$orgId/settings': {
      id: '/_authenticated/orgs/$orgId/settings'
      path: '/settings'
      fullPath: '/orgs/$orgId/settings'
      preLoaderRoute: typeof AuthenticatedOrgsOrgIdSettingsRouteImport
      parentRoute: typeof AuthenticatedOrgsOrgIdRoute
    }
    '/_authenticated/orgs/$orgId/scan': {
      id: '/_authenticated/orgs/$orgId/scan'
      path: '/scan'
      fullPath: '/orgs/$orgId/scan'
      preLoaderRoute: typeof AuthenticatedOrgsOrgIdScanRouteImport
      parentRoute: typeof AuthenticatedOrgsOrgIdRoute
    }
    '/_authenticated/orgs/$orgId/reports': {
      id: '/_authenticated/orgs/$orgId/reports'
      path: '/reports'
      fullPath: '/orgs/$orgId/reports'
      preLoaderRoute: typeof AuthenticatedOrgsOrgIdReportsRouteImport
      parentRoute: typeof AuthenticatedOrgsOrgIdRoute
    }
    '/_authenticated/orgs/$orgId/members': {
      id: '/_authenticated/orgs/$orgId/members'
      path: '/members'
      fullPath: '/orgs/$orgId/members'
      preLoaderRoute: typeof AuthenticatedOrgsOrgIdMembersRouteImport
      parentRoute: typeof AuthenticatedOrgsOrgIdRoute
    }
    '/_authenticated/orgs/$orgId/entries': {
      id: '/_authenticated/orgs/$orgId/entries'
      path: '/entries'
      fullPath: '/orgs/$orgId/entries'
      preLoaderRoute: typeof AuthenticatedOrgsOrgIdEntriesRouteImport
      parentRoute: typeof AuthenticatedOrgsOrgIdRoute
    }
    '/_authenticated/orgs/$orgId/bank': {
      id: '/_authenticated/orgs/$orgId/bank'
      path: '/bank'
      fullPath: '/orgs/$orgId/bank'
      preLoaderRoute: typeof AuthenticatedOrgsOrgIdBankRouteImport
      parentRoute: typeof AuthenticatedOrgsOrgIdRoute
    }
    '/_authenticated/orgs/$orgId/attachments': {
      id: '/_authenticated/orgs/$orgId/attachments'
      path: '/attachments'
      fullPath: '/orgs/$orgId/attachments'
      preLoaderRoute: typeof AuthenticatedOrgsOrgIdAttachmentsRouteImport
      parentRoute: typeof AuthenticatedOrgsOrgIdRoute
    }
    '/_authenticated/orgs/$orgId/api-keys': {
      id: '/_authenticated/orgs/$orgId/api-keys'
      path: '/api-keys'
      fullPath: '/orgs/$orgId/api-keys'
      preLoaderRoute: typeof AuthenticatedOrgsOrgIdApiKeysRouteImport
      parentRoute: typeof AuthenticatedOrgsOrgIdRoute
    }
    '/_authenticated/orgs/$orgId/invoices/': {
      id: '/_authenticated/orgs/$orgId/invoices/'
      path: '/invoices'
      fullPath: '/orgs/$orgId/invoices/'
      preLoaderRoute: typeof AuthenticatedOrgsOrgIdInvoicesIndexRouteImport
      parentRoute: typeof AuthenticatedOrgsOrgIdRoute
    }
    '/api/public/v1/reports/summary': {
      id: '/api/public/v1/reports/summary'
      path: '/api/public/v1/reports/summary'
      fullPath: '/api/public/v1/reports/summary'
      preLoaderRoute: typeof ApiPublicV1ReportsSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/invoices/$invoiceId': {
      id: '/api/public/v1/invoices/$invoiceId'
      path: '/$invoiceId'
      fullPath: '/api/public/v1/invoices/$invoiceId'
      preLoaderRoute: typeof ApiPublicV1InvoicesInvoiceIdRouteImport
      parentRoute: typeof ApiPublicV1InvoicesRoute
    }
    '/api/public/v1/entries/$entryId': {
      id: '/api/public/v1/entries/$entryId'
      path: '/$entryId'
      fullPath: '/api/public/v1/entries/$entryId'
      preLoaderRoute: typeof ApiPublicV1EntriesEntryIdRouteImport
      parentRoute: typeof ApiPublicV1EntriesRoute
    }
    '/api/public/v1/attachments/$attachmentId': {
      id: '/api/public/v1/attachments/$attachmentId'
      path: '/$attachmentId'
      fullPath: '/api/public/v1/attachments/$attachmentId'
      preLoaderRoute: typeof ApiPublicV1AttachmentsAttachmentIdRouteImport
      parentRoute: typeof ApiPublicV1AttachmentsRoute
    }
    '/api/public/v1/ai/scan-receipt': {
      id: '/api/public/v1/ai/scan-receipt'
      path: '/api/public/v1/ai/scan-receipt'
      fullPath: '/api/public/v1/ai/scan-receipt'
      preLoaderRoute: typeof ApiPublicV1AiScanReceiptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/orgs/$orgId/invoices/$invoiceId': {
      id: '/_authenticated/orgs/$orgId/invoices/$invoiceId'
      path: '/invoices/$invoiceId'
      fullPath: '/orgs/$orgId/invoices/$invoiceId'
      preLoaderRoute: typeof AuthenticatedOrgsOrgIdInvoicesInvoiceIdRouteImport
      parentRoute: typeof AuthenticatedOrgsOrgIdRoute
    }
    '/_authenticated/orgs/$orgId/bank_/diagnostics': {
      id: '/_authenticated/orgs/$orgId/bank_/diagnostics'
      path: '/bank/diagnostics'
      fullPath: '/orgs/$orgId/bank/diagnostics'
      preLoaderRoute: typeof AuthenticatedOrgsOrgIdBankDiagnosticsRouteImport
      parentRoute: typeof AuthenticatedOrgsOrgIdRoute
    }
    '/_authenticated/orgs/$orgId/bank_/callback': {
      id: '/_authenticated/orgs/$orgId/bank_/callback'
      path: '/bank/callback'
      fullPath: '/orgs/$orgId/bank/callback'
      preLoaderRoute: typeof AuthenticatedOrgsOrgIdBankCallbackRouteImport
      parentRoute: typeof AuthenticatedOrgsOrgIdRoute
    }
    '/api/public/v1/invoices/$invoiceId/send': {
      id: '/api/public/v1/invoices/$invoiceId/send'
      path: '/send'
      fullPath: '/api/public/v1/invoices/$invoiceId/send'
      preLoaderRoute: typeof ApiPublicV1InvoicesInvoiceIdSendRouteImport
      parentRoute: typeof ApiPublicV1InvoicesInvoiceIdRoute
    }
    '/api/public/v1/invoices/$invoiceId/pdf': {
      id: '/api/public/v1/invoices/$invoiceId/pdf'
      path: '/pdf'
      fullPath: '/api/public/v1/invoices/$invoiceId/pdf'
      preLoaderRoute: typeof ApiPublicV1InvoicesInvoiceIdPdfRouteImport
      parentRoute: typeof ApiPublicV1InvoicesInvoiceIdRoute
    }
    '/api/public/v1/entries/$entryId/attachments': {
      id: '/api/public/v1/entries/$entryId/attachments'
      path: '/attachments'
      fullPath: '/api/public/v1/entries/$entryId/attachments'
      preLoaderRoute: typeof ApiPublicV1EntriesEntryIdAttachmentsRouteImport
      parentRoute: typeof ApiPublicV1EntriesEntryIdRoute
    }
  }
}

interface AuthenticatedOrgsOrgIdRouteChildren {
  AuthenticatedOrgsOrgIdApiKeysRoute: typeof AuthenticatedOrgsOrgIdApiKeysRoute
  AuthenticatedOrgsOrgIdAttachmentsRoute: typeof AuthenticatedOrgsOrgIdAttachmentsRoute
  AuthenticatedOrgsOrgIdBankRoute: typeof AuthenticatedOrgsOrgIdBankRoute
  AuthenticatedOrgsOrgIdEntriesRoute: typeof AuthenticatedOrgsOrgIdEntriesRoute
  AuthenticatedOrgsOrgIdMembersRoute: typeof AuthenticatedOrgsOrgIdMembersRoute
  AuthenticatedOrgsOrgIdReportsRoute: typeof AuthenticatedOrgsOrgIdReportsRoute
  AuthenticatedOrgsOrgIdScanRoute: typeof AuthenticatedOrgsOrgIdScanRoute
  AuthenticatedOrgsOrgIdSettingsRoute: typeof AuthenticatedOrgsOrgIdSettingsRoute
  AuthenticatedOrgsOrgIdIndexRoute: typeof AuthenticatedOrgsOrgIdIndexRoute
  AuthenticatedOrgsOrgIdBankCallbackRoute: typeof AuthenticatedOrgsOrgIdBankCallbackRoute
  AuthenticatedOrgsOrgIdBankDiagnosticsRoute: typeof AuthenticatedOrgsOrgIdBankDiagnosticsRoute
  AuthenticatedOrgsOrgIdInvoicesInvoiceIdRoute: typeof AuthenticatedOrgsOrgIdInvoicesInvoiceIdRoute
  AuthenticatedOrgsOrgIdInvoicesIndexRoute: typeof AuthenticatedOrgsOrgIdInvoicesIndexRoute
}

const AuthenticatedOrgsOrgIdRouteChildren: AuthenticatedOrgsOrgIdRouteChildren =
  {
    AuthenticatedOrgsOrgIdApiKeysRoute: AuthenticatedOrgsOrgIdApiKeysRoute,
    AuthenticatedOrgsOrgIdAttachmentsRoute:
      AuthenticatedOrgsOrgIdAttachmentsRoute,
    AuthenticatedOrgsOrgIdBankRoute: AuthenticatedOrgsOrgIdBankRoute,
    AuthenticatedOrgsOrgIdEntriesRoute: AuthenticatedOrgsOrgIdEntriesRoute,
    AuthenticatedOrgsOrgIdMembersRoute: AuthenticatedOrgsOrgIdMembersRoute,
    AuthenticatedOrgsOrgIdReportsRoute: AuthenticatedOrgsOrgIdReportsRoute,
    AuthenticatedOrgsOrgIdScanRoute: AuthenticatedOrgsOrgIdScanRoute,
    AuthenticatedOrgsOrgIdSettingsRoute: AuthenticatedOrgsOrgIdSettingsRoute,
    AuthenticatedOrgsOrgIdIndexRoute: AuthenticatedOrgsOrgIdIndexRoute,
    AuthenticatedOrgsOrgIdBankCallbackRoute:
      AuthenticatedOrgsOrgIdBankCallbackRoute,
    AuthenticatedOrgsOrgIdBankDiagnosticsRoute:
      AuthenticatedOrgsOrgIdBankDiagnosticsRoute,
    AuthenticatedOrgsOrgIdInvoicesInvoiceIdRoute:
      AuthenticatedOrgsOrgIdInvoicesInvoiceIdRoute,
    AuthenticatedOrgsOrgIdInvoicesIndexRoute:
      AuthenticatedOrgsOrgIdInvoicesIndexRoute,
  }

const AuthenticatedOrgsOrgIdRouteWithChildren =
  AuthenticatedOrgsOrgIdRoute._addFileChildren(
    AuthenticatedOrgsOrgIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedOrgsOrgIdRoute: typeof AuthenticatedOrgsOrgIdRouteWithChildren
  AuthenticatedOrgsNewRoute: typeof AuthenticatedOrgsNewRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedOrgsOrgIdRoute: AuthenticatedOrgsOrgIdRouteWithChildren,
  AuthenticatedOrgsNewRoute: AuthenticatedOrgsNewRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ApiPublicV1AttachmentsRouteChildren {
  ApiPublicV1AttachmentsAttachmentIdRoute: typeof ApiPublicV1AttachmentsAttachmentIdRoute
}

const ApiPublicV1AttachmentsRouteChildren: ApiPublicV1AttachmentsRouteChildren =
  {
    ApiPublicV1AttachmentsAttachmentIdRoute:
      ApiPublicV1AttachmentsAttachmentIdRoute,
  }

const ApiPublicV1AttachmentsRouteWithChildren =
  ApiPublicV1AttachmentsRoute._addFileChildren(
    ApiPublicV1AttachmentsRouteChildren,
  )

interface ApiPublicV1EntriesEntryIdRouteChildren {
  ApiPublicV1EntriesEntryIdAttachmentsRoute: typeof ApiPublicV1EntriesEntryIdAttachmentsRoute
}

const ApiPublicV1EntriesEntryIdRouteChildren: ApiPublicV1EntriesEntryIdRouteChildren =
  {
    ApiPublicV1EntriesEntryIdAttachmentsRoute:
      ApiPublicV1EntriesEntryIdAttachmentsRoute,
  }

const ApiPublicV1EntriesEntryIdRouteWithChildren =
  ApiPublicV1EntriesEntryIdRoute._addFileChildren(
    ApiPublicV1EntriesEntryIdRouteChildren,
  )

interface ApiPublicV1EntriesRouteChildren {
  ApiPublicV1EntriesEntryIdRoute: typeof ApiPublicV1EntriesEntryIdRouteWithChildren
}

const ApiPublicV1EntriesRouteChildren: ApiPublicV1EntriesRouteChildren = {
  ApiPublicV1EntriesEntryIdRoute: ApiPublicV1EntriesEntryIdRouteWithChildren,
}

const ApiPublicV1EntriesRouteWithChildren =
  ApiPublicV1EntriesRoute._addFileChildren(ApiPublicV1EntriesRouteChildren)

interface ApiPublicV1InvoicesInvoiceIdRouteChildren {
  ApiPublicV1InvoicesInvoiceIdPdfRoute: typeof ApiPublicV1InvoicesInvoiceIdPdfRoute
  ApiPublicV1InvoicesInvoiceIdSendRoute: typeof ApiPublicV1InvoicesInvoiceIdSendRoute
}

const ApiPublicV1InvoicesInvoiceIdRouteChildren: ApiPublicV1InvoicesInvoiceIdRouteChildren =
  {
    ApiPublicV1InvoicesInvoiceIdPdfRoute: ApiPublicV1InvoicesInvoiceIdPdfRoute,
    ApiPublicV1InvoicesInvoiceIdSendRoute:
      ApiPublicV1InvoicesInvoiceIdSendRoute,
  }

const ApiPublicV1InvoicesInvoiceIdRouteWithChildren =
  ApiPublicV1InvoicesInvoiceIdRoute._addFileChildren(
    ApiPublicV1InvoicesInvoiceIdRouteChildren,
  )

interface ApiPublicV1InvoicesRouteChildren {
  ApiPublicV1InvoicesInvoiceIdRoute: typeof ApiPublicV1InvoicesInvoiceIdRouteWithChildren
}

const ApiPublicV1InvoicesRouteChildren: ApiPublicV1InvoicesRouteChildren = {
  ApiPublicV1InvoicesInvoiceIdRoute:
    ApiPublicV1InvoicesInvoiceIdRouteWithChildren,
}

const ApiPublicV1InvoicesRouteWithChildren =
  ApiPublicV1InvoicesRoute._addFileChildren(ApiPublicV1InvoicesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicV1AttachmentsRoute: ApiPublicV1AttachmentsRouteWithChildren,
  ApiPublicV1CompanySearchRoute: ApiPublicV1CompanySearchRoute,
  ApiPublicV1EntriesRoute: ApiPublicV1EntriesRouteWithChildren,
  ApiPublicV1InvoicesRoute: ApiPublicV1InvoicesRouteWithChildren,
  ApiPublicV1AiScanReceiptRoute: ApiPublicV1AiScanReceiptRoute,
  ApiPublicV1ReportsSummaryRoute: ApiPublicV1ReportsSummaryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
